module.exports = {
  mapData: {
    YangWoodValue: 1,
    YinWoodValue: 2,
    YangFireValue: 3,
    YinFireValue: 4,
    YangEarthValue: 5,
    YinEarthValue: 6,
    YangMetalValue: 7,
    YinMetalValue: 8,
    YangWaterValue: 9,
    YinWaterValue: 10,

    YangWoodName: "Yang Wood",
    YinWoodName: "Yin Wood",
    YangFireName: "Yang Fire",
    YinFireName: "Yin Fire",
    YangEarthName: "Yang Earth",
    YinEarthName: "Yin Earth",
    YangMetalName: "Yang Metal",
    YinMetalName: "Yin Metal",
    YangWaterName: "Yang Water",
    YinWaterName: "Yin Water",

    YangWoodCharacter: "甲",
    YinWoodCharacter: "乙",
    YangFireCharacter: "丙",
    YinFireCharacter: "丁",
    YangEarthCharacter: "戊",
    YinEarthCharacter: "己",
    YangMetalCharacter: "庚",
    YinMetalCharacter: "辛",
    YangWaterCharacter: "壬",
    YinWaterCharacter: "癸",


    "Yang WoodSpelling": "Jia",
    "Yin WoodSpelling": "Yi",
    "Yang FireSpelling": "Bing",
    "Yin FireSpelling": "Ding",
    "Yang EarthSpelling": "Wu",
    "Yin EarthSpelling": "Ji",
    "Yang MetalSpelling": "Geng",
    "Yin MetalSpelling": "Xin",
    "Yang WaterSpelling": "Ren",
    "Yin WaterSpelling": "Gui",

    // Earthly Branch default values
    TigerValue: 1,
    RabbitValue: 2,
    DragonValue: 3,
    SnakeValue: 4,
    HorseValue: 5,
    GoatValue: 6,
    MonkeyValue: 7,
    RoosterValue: 8,
    DogValue: 9,
    PigValue: 10,
    RatValue: 11,
    OxValue: 12,

    Tiger: "Tiger",
    Rabbit: "Rabbit",
    Dragon: "Dragon",
    Snake: "Snake",
    Horse: "Horse",
    Goat: "Goat",
    Monkey: "Monkey",
    Rooster: "Rooster",
    Dog: "Dog",
    Pig: "Pig",
    Rat: "Rat",
    Ox: "Ox",

    TigerCharacter: "寅",
    RabbitCharacter: "卯",
    DragonCharacter: "辰",
    SnakeCharacter: "巳",
    HorseCharacter: "午",
    GoatCharacter: "未",
    MonkeyCharacter: "申",
    RoosterCharacter: "酉",
    DogCharacter: "戌",
    PigCharacter: "亥",
    RatCharacter: "子",
    OxCharacter: "丑",

    TigerSpelling: "Yin",
    RabbitSpelling: "Mao",
    DragonSpelling: "Chen",
    SnakeSpelling: "Si",
    HorseSpelling: "Wu",
    GoatSpelling: "Wei",
    MonkeySpelling: "Shen",
    RoosterSpelling: "You",
    DogSpelling: "Xu",
    PigSpelling: "Hai",
    RatSpelling: "Zi",
    OxSpelling: "Chou"
  }
  // Heavenly Stem default values

};